"""initial migration

Revision ID: 1fd112c92a22
Revises: None
Create Date: 2015-10-18 15:11:45.929661

"""

# revision identifiers, used by Alembic.
revision = '1fd112c92a22'
down_revision = None

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    pass
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    pass
    ### end Alembic commands ###
